config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:create, :index, :destroy]

  get 'home/index'

  resources :pages do
    resources :events do
      member do
        put "like" => "events#like"
      end
    end
    member do
      put "follow" => "pages#follow"
    end
  end

  resources :profiles, only:[:index, :show, :update, :edit]

  get '/my_profile' => 'profiles#profile', as: 'my_profile'
  get '/my_pages' => 'pages#my_pages', as: 'my_pages'
  get '/my_events' => 'events#my_events', as: 'my_events'
  get '/searching' => 'user#searching', as: 'searching'

  resources :products do
    resources :stocks, only:[:index, :create]
  end
  devise_for :controllers

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get '/resultados_busqueda/:search' => 'user#search', as: 'resultados_busqueda'

  put 'follow/:id/:id2' => 'profiles#follow', as: 'follow_profile'

  resources :posts do
    resources :comments, only:[:create]

    member do
      put "like" => "posts#like"
    end
  end

  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :follow, :searching]
  load_and_authorize_resource
  skip_authorization_check

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @user_profile = User.find(params[:id])
    @posts = Post.all
    @comments = Comment.all.limit(1)
    @profiles = Profile.all
    @events = Event.all.limit(2).order("RANDOM()")
    @products = Product.all.limit(2).order("RANDOM()")
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  def profile
    @profile = current_user.profile
    @posts = Post.all
    @post = Post.new
  end

  def follow
    @user = User.find(params[:id])
    @current_profile = User.find(params[:id2])

    if current_user.following?(@user)
      current_user.follow_user(@user, false)
      # current_user.stop_following(@user)
    else
      current_user.follow_user(@user, true)
      # current_user.follow(@user)
    end
      # redirect_to profile_path(@user.profile)

  end


  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:username, :fullname, :bio, :avatar, :instagram, :facebook, :twitter, :cover)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field-avatar">
    <%= form.label :avatar, 'Seleccionar imagen de perfil' %>
    <%= form.file_field :avatar, id: :profile_avatar %>
  </div>

  <div class="field field-avatar">
    <%= form.label :cover, 'Seleccionar cover' %>
    <%= form.file_field :cover, id: :profile_cover %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :profile_username %>
  </div>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, id: :profile_fullname %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="field">
    <%= form.label :instagram %>
    <%= form.text_field :instagram, id: :profile_instagram %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook, id: :profile_facebook %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, id: :profile_twitter %>
  </div>


  <div class="actions">
    <%= form.submit "Publicar" %>
  </div>
<% end %>

app/views/profiles/create.js.erb
console.log('busqueda');

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/follow.js.erb
$('#follow-btn').html('');

  <% if current_user.following?(@user) %>
    $('#follow-btn-<%= @user.id %>').html("<%= j link_to 'Dejar de seguir', follow_profile_path(@user.id, @current_profile.id), method: :put, class: 'disable', remote: true %>");
    $('#btn-siguiendo-<%= @user.id %>').html('<a class="disable" data-remote="true" rel="nofollow" data-method="put" href="/follow/<%= @user.id %>/<%= @current_profile.id %>">siguiendo</a>');
  <% else %>
    $('#follow-btn-<%= @user.id %>').html("<%= j link_to 'Seguir', follow_profile_path(@user.id, @current_profile.id), method: :put, remote: true %>");
    $('#btn-siguiendo-<%= @user.id %>').html('<a class="active-follow" data-remote="true" rel="nofollow" data-method="put" href="/follow/<%= @user.id %>/<%= @current_profile.id %>">Seguir</a>');
  <% end %>

$('#follow-count-<%= @current_profile.id %>').html("<%= @current_profile.followers.count %>");
$('#following-count-<%= @current_profile.id %>').html("<%= @current_profile.all_following.count %>");

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Fullname</th>
      <th>Bio</th>
      <th>User</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= profile.fullname %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.user %></td>
        <td><%= profile.avatar %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/profile.html.erb
<section class="wrap-edit-profile">
  <section class="wrap-edit-profile-center">

    <h1>Editar perfil</h1>
    <p>Aquí podrás editar tu perfil, cambiar datos y los accesos a tus cuentas de redes sociales</p>

    <div id="tabs-container">

        <ul class="tabs-menu">
            <li class="current"><a href="#tab-1">Perfil</a></li>
        </ul>

        <div class="tab">

            <div id="tab-1" class="tab-content">

              <%= render 'form', profile: @profile %>

            </div>


        </div>
    </div>

  </section>
</section>

<%= render 'partials/footer-inter' %>

app/views/profiles/show.html.erb
<section class="header-user-profile">
    <section class="bg-cover" style="background-image: url(<%= @profile.cover %>);"></section>
    <section class="header-user-profile-center">
       <section class="main-profile-info-container">
            <section class="profile-info">

               <a class="image-profile" style="background-image: url(<%= @profile.avatar %>);"></a>
                <article class="info">
                    <h1><%= @profile.username %></h1>

                    <% if current_user == @profile.user %>

                      <%= link_to my_profile_path, class:"editar" do %>
                         <i class="far fa-edit"></i> Editar Perfil
                       <% end %>
                    <% end %>

                    <p><span><%= @user_profile.profile.fullname %></span>
                      <%= @profile.bio %></p>

                    <% if current_user != @profile.user %>
                    <div id="follow-btn-<%= @profile.user.id %>">

                        <% if current_user.following?(@profile.user) %>
                          <div class="follow-blo">
                            <p class="siguiendo"><i class="fas fa-user-plus"></i> Siguiendo</p>
                            <%= link_to 'Dejar de seguir', follow_profile_path(@profile.user, @profile.user), method: :put, class: 'disable', remote: true %>
                          </div>
                        <% else %>
                          <%= link_to 'Seguir', follow_profile_path(@profile.user, @profile.user), method: :put, remote: true %>
                        <% end %>

                    </div>
                    <% end %>

                </article>
            </section>

            <section class="profile-info-foot">
                <section class="follows-dats">
                    <a href="#" data-toggle="modal" data-target="#modalFriendsSeguidores"><span id="follow-count-<%= @profile.user.id %>"><%= @profile.user.followers.count %></span> seguidores</a>
                    <a href="#" data-toggle="modal" data-target="#modalFriends"><span id="following-count-<%= @profile.user.id %>"><%= @profile.user.all_following.count %> </span> seguidos</a>
                </section>

                <!-- Modal de amigos seguidores -->
                <div class="modal fade modal-custom" id="modalFriendsSeguidores" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-custom" role="document">
                    <div class="modal-content modal-content-custom">

                      <h1>Seguidores</h1>

                      <% @profile.user.followers_by_type('User').each do |user_profile| %>
                         <%= render 'partials/follower-profile-seguidores', user_profile: user_profile.profile %>
                      <% end %>

                    </div>
                  </div>
                </div>

                <!-- Modal de amigos seguidos -->
                <div class="modal fade modal-custom" id="modalFriends" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-custom" role="document">
                    <div class="modal-content modal-content-custom">

                      <h1>Seguidos</h1>

                      <% @profile.user.following_by_type('User').each do |user_profile| %>
                         <%= render 'partials/follower-profile-seguidos', user_profile: user_profile.profile %>
                      <% end %>

                    </div>
                  </div>
                </div>



                <section class="social-menu">
                    <nav>
                        <ul>
                            <% if @profile.instagram != '' %>
                              <li> <a href="https://www.instagram.com/<%= @profile.instagram %>" target="_blank"><i class="fab fa-instagram"></i></a> </li>
                            <% end %>
                            <% if @profile.facebook != '' %>
                              <li> <a href="https://www.facebook.com/<%= @profile.facebook %>" target="_blank"><i class="fab fa-facebook-f"></i></a> </li>
                            <% end %>
                            <% if @profile.twitter != '' %>
                              <li> <a href="https://www.twitter.com/<%= @profile.twitter %>" target="_blank"><i class="fab fa-twitter"></i></a> </li>
                            <% end %>
                        </ul>
                    </nav>
                </section>
            </section>
        </section>
    </section>
</section>


<section class="wrap-profile">
    <section class="wrap-profile-center">

       <div id="tabs-container">

        <ul class="tabs-menu">
            <li class="current"><a href="#tab-1">publicaciones</a></li>
        </ul>

        <div class="tab">

            <div id="tab-1" class="tab-content">

              <section class="post">

                 <article class="publicar">

                  <h1>crear una publicación</h1>

                    <%= render 'posts/form', post: Post.new %>

                 </article>

                 <%= render 'partials/post-profile' %>

              </section>

              <section class="sidebar-post">
                 <article class="friend">
                     <h1>seguidores</h1>

                     <div class="grid-friends">

                         <% @profile.user.followers.each do |user_profile| %>
                            <%= render 'partials/follower-index', profile: user_profile.profile %>
                        <% end %>

                     </div>

                     <%= render 'partials/sidebar' %>

                 </article>
              </section>


            </div>



        </div>
    </div>

    </section>
</section>

<%= render 'partials/footer-inter' %>

<script>
  $(".new_comment").keyup(function (event){
    var keycode = (event.keyCode ? event.keyCode : event.which);
    if(keycode == '13'){

        // var post_id = $(this).parent().parent().attr("id");
        var post_id = $(this).attr("id").split("-")[1]
        $.ajax({
          url: '/posts/'+ post_id +'/comments',
          type: 'post',
          dataType: 'script',
          data: {content: $(this).val()}
        })
        .done(function() {
          console.log("success");
        })
        .fail(function() {
          console.log("error");
        })
        .always(function() {
          console.log("complete");
        });


    }
  })
</script>