config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:create, :index, :destroy]

  get 'home/index'

  resources :pages do
    resources :events do
      member do
        put "like" => "events#like"
      end
    end
    member do
      put "follow" => "pages#follow"
    end
  end

  resources :profiles, only:[:index, :show, :update, :edit]

  get '/my_profile' => 'profiles#profile', as: 'my_profile'
  get '/my_pages' => 'pages#my_pages', as: 'my_pages'
  get '/my_events' => 'events#my_events', as: 'my_events'
  get '/searching' => 'user#searching', as: 'searching'

  resources :products do
    resources :stocks, only:[:index, :create]
  end
  devise_for :controllers

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get '/resultados_busqueda/:search' => 'user#search', as: 'resultados_busqueda'

  put 'follow/:id/:id2' => 'profiles#follow', as: 'follow_profile'

  resources :posts do
    resources :comments, only:[:create]

    member do
      put "like" => "posts#like"
    end
  end

  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all

        can :create, Post
        can [ :edit, :update, :delete ], Post do |post|
          post.user_id == user.id
        end

        can :create, Page
        can :my_pages, Page
        can [ :edit, :update, :delete ], Page do |page|
          page.user_id == user.id
        end

        can :create, Event
        can [ :edit, :update, :delete ], Event do |event|
          event.user_id == user.id
        end

        can :manage, Profile, user_id: user.id

        can :read, Profile

        # can :edit, Event, user_id: user.id

        can :create, Comment
        can :like, Event
        can :like, Post

        #Follow
        can :follow, Profile
        can :follow, Page
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :page

  mount_uploader :eventimage, EventimageUploader

  acts_as_votable
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :stock

end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user
  has_many :events, :dependent => :destroy
  mount_uploader :image, AvatarUploader
  mount_uploader :cover, BannerUploader

  acts_as_followable

  
end

app/models/post.rb
class Post < ApplicationRecord

belongs_to :user
has_many :comments, :dependent => :destroy

acts_as_votable

def get_like_by_user( user_id)
  voterid = ''
  posts = Post.find(self.id).get_likes.by_type(User)
  posts.each do |v|
    if user_id == v.voter_id
      voterid = v.id
    end
  end
  return voterid
end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :stocks, :dependent => :destroy


  mount_uploader :imagen, ImagenUploader

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :posts, :dependent => :destroy
  has_many :products, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_one :profile, :dependent => :destroy
  has_many :pages, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :orders

  enum role: [:admin,:visit]

  after_initialize do
    if self.new_record?
      self.role ||= :visit
    end
  end

  acts_as_followable
  acts_as_follower

  acts_as_voter

  def my_posts
    followers_id = []
    self.all_following.each do |f|
      followers_id << f.id
    end
    followers_id << id
    posts = Post.where(user_id: followers_id)
    return posts
  end

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
   end
  end

  def follow_user(user, way)
    if way == true
      self.follow(user)
    else
      self.stop_following(user)
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/partials/_follower-index.html.erb
  <li>
    <%= link_to image_tag( profile.avatar , alt: "User"), profile_path(profile.user) %>
  </li>

app/views/partials/_follower-profile-seguidores.html.erb
<div class="follower-profile">

  <div class="bloque-follow">
    <%= image_tag( user_profile.avatar , alt: "User") %>
    <div class="info-name">
      <%= link_to user_profile.username, profile_path(user_profile.user) %>
      <p><%= user_profile.fullname %></p>
    </div>
  </div>

  <div class="bloque-follow">

    <% if current_user != user_profile.user %>

      <% if current_user.following?(user_profile.user) %>

        <div class="follow-blo" id="btn-siguiendo-<%= user_profile.user_id.to_s %>">
          <%= link_to 'siguiendo', follow_profile_path(user_profile.user.id, @profile.user.id), method: :put, class: 'disable', remote: true %>
        </div>

      <% else %>

        <div class="follow-blo" id="btn-siguiendo-<%= user_profile.user_id.to_s %>">
          <%= link_to 'Seguir', follow_profile_path(user_profile.user.id, @profile.user.id), method: :put, class: 'active-follow', remote: true %>
        </div>

      <% end %>

      <% end %>

  </div>

</div>

app/views/partials/_follower-profile-seguidos.html.erb
<div class="follower-profile">

  <div class="bloque-follow">
    <%= image_tag( user_profile.avatar , alt: "User") %>
    <div class="info-name">
      <%= link_to user_profile.username, profile_path(user_profile.user) %>
      <p><%= user_profile.fullname %></p>
    </div>
  </div>

  <div class="bloque-follow">

    <% if current_user != user_profile.user %>

      <% if current_user.following?(user_profile.user) %>

        <div class="follow-blo" id="btn-siguiendo-<%= user_profile.user_id.to_s %>">
          <%= link_to 'siguiendo', follow_profile_path(user_profile.user.id, @profile.user.id), method: :put, class: 'disable', remote: true %>
        </div>

      <% else %>

        <div class="follow-blo" id="btn-siguiendo-<%= user_profile.user_id.to_s %>">
          <%= link_to 'Seguir', follow_profile_path(user_profile.user.id, @profile.user.id), method: :put, class: 'active-follow', remote: true %>
        </div>

      <% end %>

      <% end %>

  </div>

</div>

app/views/partials/_follower.html.erb
<div>
  <%= link_to f.email, f.profile %>
  <%= link_to image_tag(f.profile.avatar), f.profile %>
</div>

app/views/partials/_footer-inter.html.erb
<footer class="footer-sections">
  <section class="footer-center">
    <a href="<%= home_index_path %>"> <%= image_tag("Logo-atoallae-int.svg", :alt => "Logo Atoallae") %> </a>

    <% if user_signed_in? %>
    <nav>
      <ul>
        <%= link_to 'Actividad', posts_path, class: 'dropdown-item' %>
        <%= link_to 'Mis paginas', my_pages_path, class: 'dropdown-item' %>
        <%= link_to 'Paginas', pages_path, class: 'dropdown-item' %>
        <%= link_to 'Store', products_path, class: 'dropdown-item' %>
        <% if current_user.admin? %>
          <%= link_to 'Nuevo Producto', new_product_path, class: 'dropdown-item' %>
        <% end %>
        <a href="<%= destroy_user_session_path %>" data-method="DELETE" class="dropdown-item">Cerrar Sesión</a>
      </ul>
    </nav>
    <% else %>

    <nav class="no-registro-nav">
        <ul>
            <li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
            <li><a href="<%= new_user_registration_path %>" class="main-link">Crear Cuenta</a></li>
            <li><a href="https://www.instagram.com/atoallae/" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://www.facebook.com/atoallae/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
        </ul>
    </nav>

    <% end %>

    <p class="credits">Derechos Reservados © <span>atoallae</span> 2020 - 2021, Santiago Chile </p>

  </section>
</footer>

app/views/partials/_footer-store.html.erb
<footer class="footer-store">
  <section class="footer-center">
    <a href="<%= home_index_path %>"> <%= image_tag("Logo-atoallae-int.svg", :alt => "Logo Atoallae") %> </a>

    <% if user_signed_in? %>
    <nav>
      <ul>
        <%= link_to 'Actividad', posts_path, class: 'dropdown-item' %>
        <%= link_to 'Mis paginas', my_pages_path, class: 'dropdown-item' %>
        <%= link_to 'Paginas', pages_path, class: 'dropdown-item' %>
        <%= link_to 'Store', products_path, class: 'dropdown-item' %>
        <% if current_user.admin? %>
          <%= link_to 'Nuevo Producto', new_product_path, class: 'dropdown-item' %>
        <% end %>
        <a href="<%= destroy_user_session_path %>" data-method="DELETE" class="dropdown-item">Cerrar Sesión</a>
      </ul>
    </nav>
    <% else %>

    <nav class="no-registro-nav">
        <ul>
            <li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
            <li><a href="<%= new_user_registration_path %>" class="main-link">Crear Cuenta</a></li>
            <li><a href="https://www.instagram.com/atoallae/" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://www.facebook.com/atoallae/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
        </ul>
    </nav>

    <% end %>

    <p class="credits">Derechos Reservados © <span>atoallae</span> 2020 - 2021, Santiago Chile </p>

  </section>
</footer>

app/views/partials/_footer.html.erb
<footer class="footer-home">
  <section class="footer-center">
    <a href="<%= home_index_path %>"> <%= image_tag("Logo-atoallae-int.svg", :alt => "Logo Atoallae") %> </a>

    <% if user_signed_in? %>
    <nav>
      <ul>
        <%= link_to 'Actividad', posts_path, class: 'dropdown-item' %>
        <%= link_to 'Mis paginas', my_pages_path, class: 'dropdown-item' %>
        <%= link_to 'Paginas', pages_path, class: 'dropdown-item' %>
        <%= link_to 'Store', products_path, class: 'dropdown-item' %>
        <% if current_user.admin? %>
          <%= link_to 'Nuevo Producto', new_product_path, class: 'dropdown-item' %>
        <% end %>
        <a href="<%= destroy_user_session_path %>" data-method="DELETE" class="dropdown-item">Cerrar Sesión</a>
      </ul>
    </nav>
    <% else %>

    <nav class="no-registro-nav">
        <ul>
            <li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
            <li><a href="<%= new_user_registration_path %>" class="main-link">Crear Cuenta</a></li>
            <li><a href="https://www.instagram.com/atoallae/" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://www.facebook.com/atoallae/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
        </ul>
    </nav>

    <% end %>

    <p class="credits">Derechos Reservados © <span>atoallae</span> 2020 - 2021, Santiago Chile </p>

  </section>
</footer>

app/views/partials/_navbar.html.erb
<header class="main-header">

  <% if user_signed_in? %>

  <section class="header-inter-center">

     <nav class="navbar navbar-expand-lg container-fullwidth custom-nav">

      <a href="<%= home_index_path %>"> <%= image_tag("Logo-atoallae-int.svg", :alt => "Logo Atoallae") %> </a>

       <div class="der-bloque">


       <div class="user-top-info">
           <a href="<%= profile_path(current_user.profile) %>" style="background-image: url(<%= current_user.profile.avatar %>);" class="user"></a>
           <span><%= current_user.profile.fullname %></span>

           <%= link_to 'Actividad', posts_path, class: 'activity-navbar' %>
       </div>

       <button id="search-btn"><i class="fas fa-search"></i></button>

         <% if current_user.orders.count > 0 %>
           <a href="<%= orders_path %>" class="cart"><%= image_tag("cart-active.svg", :alt => "Carrito compra") %></a>
         <% else %>
           <a href="<%= orders_path %>" class="cart"><%= image_tag("cart.svg", :alt => "Carrito compra") %></a>
         <% end %>

         <a href="" class="bell">
             <%= image_tag("bell.svg", :alt => "Bell icon") %>
         </a>

       <div class="dropdown ">

          <button class="btn nav-custom-btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag("menu.svg", :alt => "Menu") %>
          </button>
          <div class="dropdown-menu show-custom" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Actividad', posts_path, class: 'dropdown-item' %>
            <%= link_to 'Mis paginas', my_pages_path, class: 'dropdown-item' %>
            <%= link_to 'Paginas', pages_path, class: 'dropdown-item' %>
            <%= link_to 'Store', products_path, class: 'dropdown-item' %>
            <% if current_user.admin? %>
              <%= link_to 'Nuevo Producto', new_product_path, class: 'dropdown-item' %>
            <% end %>
            <a href="<%= destroy_user_session_path %>" data-method="DELETE" class="dropdown-item">Cerrar Sesión</a>
          </div>
        </div>

        </div>
    </nav>

   </section>

  <% else %>

  <a href="<%= home_index_path %>"> <%= image_tag("Logo-atoallae.svg", :alt => "Logo Atoallae") %> </a>

  <nav>
      <ul>
          <li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
          <li><a href="<%= new_user_registration_path %>" class="main-link">Crear Cuenta</a></li>
          <li><a href="https://www.instagram.com/atoallae/" target="_blank"><i class="fab fa-instagram"></i></a></li>
          <li><a href="https://www.facebook.com/atoallae/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
      </ul>
  </nav>

  <% end %>

  <section class="search" id="search-block">
    <section class="center-search">
      <p><%= image_tag("Logo-atoallae-int.svg", :alt => "Logo Atoallae") %>
        Haz una busqueda entre nuestros usuarios y encuentra a tus amigos</p>

      <%= form_tag searching_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: 'Buscar Amigos' %>
        <%= button_tag type: 'submit', name: nil  do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>

      <a href="" class="close-form"> <%= image_tag("close.svg", :alt => "cerrar buscador") %> </a>

    </section>
  </section>

</header>

app/views/partials/_post-profile.html.erb
<% @profile.user.posts.reverse_each do |post| %>

<article class="post-users">
  <% if current_user == post.user %>
  <nav class="navbar navbar-expand-lg navbar-custom">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-h"></i>
          </a>
          <div class="dropdown-menu show-custom" aria-labelledby="navbarDropdown">

            <%= link_to 'Editar Post', edit_post_path(post), class: 'dropdown-item' %>
            <%= link_to 'Eliminar Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>


          </div>
        </li>
      </ul>
    </div>
  </nav>

  <% end %>

      <div class="post-user-header">
          <a href="<%= profile_path(post.user.profile) %>" style="background-image: url(<%= post.user.profile.avatar %>);"></a>
          <div class="info-user-header">

              <%= link_to post.user.profile.fullname, profile_path(post.user.profile), class: 'name-user' %>
              <a href="#" class="date">25 feb 2020</a>
          </div>
      </div>
      <div class="post-user-content-body">
          <p><%= post.texto %></p>
      </div>
      <div class="post-user-footer">

    <div class="info-feed">

      <div class="bloque">

          <%= link_to image_tag( (current_user.liked? post)? 'heart-active.svg' :'heart.svg', alt: "Heart active like icon"), like_post_path(post), class: 'heart-'+ post.id.to_s, method: :put, remote: true %>
          <span class="likescount-<%= post.id %>"><%= post.get_likes.size %></span>



          <%= link_to post do %>
          <%= image_tag("comment.svg", :alt => "Comment Icon") %>
          <span id="total-comments-<%= post.id %>"><%= post.comments.count %></span>
          <% end %>
      </div>

      <div class="bloque-2">
        <nav id="like-aj-img-<%= post.id.to_s %>">
          <% post.get_likes.by_type(User)[0,3].each  do |image| %>
            <%= link_to "#", :id => 'user_like'+post.id.to_s+"-"+image.id.to_s, "data-toggle" => "modal", 'data-target' => '#modalLikes'+post.id.to_s do %>
              <%= image_tag( image.voter.profile.avatar, :alt => "Comment Icon") %>
            <% end %>
          <% end %>
        </nav>

          <p class="section-users-<%= post.id %>">

             <% if (post.get_likes.by_type(User).count > 0 && post.get_likes.by_type(User).count == 1) %>
               <span class="name"><%= post.get_likes.by_type(User).last.voter.profile.username %></span> le gusta esto

             <% elsif (post.get_likes.by_type(User).count > 1 ) %>
               <span class="name"><%= post.get_likes.by_type(User).last.voter.profile.username %></span> y a <span class="num" id="like-aj-count"><%=(post.get_likes.size.to_i - 1) %></span> personas más les gusta esto
             <% else %>

             <% end %>

          </p>

      </div>

    </div>

    <!-- Modal de amigos que han dado like -->
    <div class="modal fade modal-custom" id="modalLikes<%= post.id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-custom">

          <h1>Amigos que les gusta tu post</h1>

          <nav id="like-aj-img-modal-<%= post.id.to_s %>" class="likes-modal">

            <% post.get_likes.by_type(User)[0,3].each  do |usermodal| %>
              <%= link_to profile_path(usermodal.voter), :id => 'user_like_modal'+post.id.to_s+"-"+usermodal.id.to_s do %>
                <%= image_tag( usermodal.voter.profile.avatar, :alt => "Comment Icon") %>

                <p><%= usermodal.voter.profile.username %>
                <span><%= usermodal.voter.profile.fullname %></span></p>


              <% end %>
            <% end %>

          </nav>

        </div>
      </div>
    </div>

    <% if post.comments.count > 0 %>
    <div class="comment-feeds">
        <a href="#" style="background-image: url(<%= post.comments.last.user.profile.avatar %>);" class="comment-img-<%= post.id %>"></a>

        <div class="comment-write comment-write-<%= post.id %>">
            <h1><%= post.comments.last.user.profile.username %></h1>
            <p><%= post.comments.last.content %></p>
            <!-- <a href=""> <img src="images/heart.svg" alt=""> <span>30</span> </a> -->
        </div>

    </div>

    <div class="comment-feeds">
        <%= link_to post, class: 'mas-comment' do%>
          <%= image_tag("comment.svg", :alt => "Comment Icon") %> Ver más comentarios
        <% end %>
    </div>
    <% end %>



    <div class="user-comment">

        <a href="<%= my_profile_path %>" style="background-image: url(<%= current_user.profile.avatar %>);" class="user"></a>

        <% if user_signed_in? %>
        <input id="new_comment-<%= post.id %>" type="text" class="new_comment" placeholder="Escribe un comentario">
        <% else %>
          Para comentar, debes estar <a href="<%= new_user_session_path %>">logeado</a>
        <% end %>

    </div>

    </div>

</article>
<% end %>

app/views/partials/_post.html.erb
<% current_user.my_posts.reverse_each do |post| %>

<article class="post-users">

  <% if current_user == post.user %>

  <nav class="navbar navbar-expand-lg navbar-custom">
    <div class="collapse navbar-collapse navbar-collapse-custom" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-h"></i>
          </a>
          <div class="dropdown-menu show-custom" aria-labelledby="navbarDropdown">

            <%= link_to 'Editar Post', edit_post_path(post), class: 'dropdown-item' %>
            <%= link_to 'Eliminar Post', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>

          </div>
        </li>
      </ul>
    </div>
  </nav>

  <% end %>

      <div class="post-user-header">
          <a href="<%= profile_path(post.user.profile) %>" style="background-image: url(<%= post.user.profile.avatar %>);"></a>
          <div class="info-user-header">

              <%= link_to post.user.profile.fullname, profile_path(post.user.profile), class: 'name-user' %>
              <a href="#" class="date">25 feb 2020</a>
          </div>
      </div>
      <div class="post-user-content-body">
          <p><%= post.texto %></p>
      </div>
      <div class="post-user-footer">

    <div class="info-feed">

        <div class="bloque">

            <%= link_to image_tag( (current_user.liked? post)? 'heart-active.svg' :'heart.svg', alt: "Heart active like icon"), like_post_path(post), class: 'heart-'+ post.id.to_s, method: :put, remote: true %>
            <span class="likescount-<%= post.id %>"><%= post.get_likes.size %></span>



            <%= link_to post do %>
            <%= image_tag("comment.svg", :alt => "Comment Icon") %>
              <span id="total-comments-<%= post.id %>"><%= post.comments.count %></span>
            <% end %>
        </div>

        <div class="bloque-2">
            <nav id="like-aj-img-<%= post.id.to_s %>">
              <% post.get_likes.by_type(User)[0,3].each  do |image| %>
                <%= link_to "#", :id => 'user_like'+post.id.to_s+"-"+image.id.to_s, "data-toggle" => "modal", 'data-target' => '#modalLikes'+post.id.to_s do %>
                  <%= image_tag( image.voter.profile.avatar, :alt => "Comment Icon") %>
                <% end %>
              <% end %>
            </nav>

            <p class="section-users-<%= post.id %>">

               <% if (post.get_likes.by_type(User).count > 0 && post.get_likes.by_type(User).count == 1) %>
                 <span class="name"><%= post.get_likes.by_type(User).last.voter.profile.username %></span> le gusta esto

               <% elsif (post.get_likes.by_type(User).count > 1 ) %>
                 <span class="name"><%= post.get_likes.by_type(User).last.voter.profile.username %></span> y a <span class="num" id="like-aj-count"><%=(post.get_likes.size.to_i - 1) %></span> personas más les gusta esto

               <% else %>

               <% end %>

            </p>

        </div>

    </div>

    <!-- Modal de amigos que han dado like -->
    <div class="modal fade modal-custom" id="modalLikes<%= post.id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-custom">

          <h1>Amigos que les gusta tu post</h1>

          <nav id="like-aj-img-modal-<%= post.id.to_s %>" class="likes-modal">

            <% post.get_likes.by_type(User)[0,3].each  do |usermodal| %>
              <%= link_to profile_path(usermodal.voter), :id => 'user_like_modal'+post.id.to_s+"-"+usermodal.id.to_s do %>
                <%= image_tag( usermodal.voter.profile.avatar, :alt => "Comment Icon") %>

                <p><%= usermodal.voter.profile.username %>
                <span><%= usermodal.voter.profile.fullname %></span></p>


              <% end %>
            <% end %>

          </nav>

        </div>
      </div>
    </div>

    <% if post.comments.count > 0 %>
    <div class="comment-feeds">
        <a href="#" style="background-image: url(<%= post.comments.last.user.profile.avatar %>);" class="comment-img-<%= post.id %>"></a>

        <div class="comment-write comment-write-<%= post.id %>">
            <h1><%= post.comments.last.user.profile.username %></h1>
            <p><%= post.comments.last.content %></p>
            <!-- <a href=""> <img src="images/heart.svg" alt=""> <span>30</span> </a> -->
        </div>

    </div>

    <div class="comment-feeds">
        <%= link_to post, class: 'mas-comment' do%>
          <%= image_tag("comment.svg", :alt => "Comment Icon") %> Ver más comentarios
        <% end %>
    </div>

    <% end %>

    <div class="user-comment">

        <a href="<%= my_profile_path %>" style="background-image: url(<%= current_user.profile.avatar %>);" class="user"></a>

        <% if user_signed_in? %>
        <input id="new_comment-<%= post.id %>" type="text" class="new_comment" placeholder="Escribe un comentario">
        <% else %>
          Para comentar, debes estar <a href="<%= new_user_session_path %>">logeado</a>
        <% end %>

    </div>

    </div>

</article>
<% end %>