config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:create, :index, :destroy]

  get 'home/index'

  resources :pages do
    resources :events do
      member do
        put "like" => "events#like"
      end
    end
    member do
      put "follow" => "pages#follow"
    end
  end

  resources :profiles, only:[:index, :show, :update, :edit]

  get '/my_profile' => 'profiles#profile', as: 'my_profile'
  get '/my_pages' => 'pages#my_pages', as: 'my_pages'
  get '/my_events' => 'events#my_events', as: 'my_events'
  get '/searching' => 'user#searching', as: 'searching'

  resources :products do
    resources :stocks, only:[:index, :create]
  end
  devise_for :controllers

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get '/resultados_busqueda/:search' => 'user#search', as: 'resultados_busqueda'

  put 'follow/:id/:id2' => 'profiles#follow', as: 'follow_profile'

  resources :posts do
    resources :comments, only:[:create]

    member do
      put "like" => "posts#like"
    end
  end

  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :page

  mount_uploader :eventimage, EventimageUploader

  acts_as_votable
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  skip_authorization_check

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @profiles = Profile.all
  end

  # GET /events/new
  def new
    @event = Event.new
    @page = Page.find(params[:page_id])
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @page = Page.find(params[:page_id])
  end

  def my_events
    @my_events = current_user.events
  end

  def like
    @event = Event.find(params[:id])
      if current_user.liked? @event
        @event.unliked_by current_user
      else
        @event.liked_by current_user
      end
    redirect_to page_event_path(@event.page, @event)
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.page = Page.find(params[:page_id])

    respond_to do |format|
      if @event.save
        format.html { redirect_to page_event_path(@event.page, @event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to page_event_path(@event.page), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to page_events_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :place, :date, :eventimage, :map)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: [@page, @event], local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :título %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :descripción %>
    <%= form.text_field :description, id: :event_description %>
  </div>

  <div class="field field-avatar">
    <%= form.label :eventimage, 'Seleccionar imagen' %>
    <%= form.file_field :eventimage, id: :event_eventimage %>
  </div>

  <div class="field">
    <%= form.label :lugar %>
    <%= form.text_field :place, id: :event_place %>
  </div>

  <div class="field">
    <%= form.label :dirección %>
    <%= form.text_field :map, id: :event_map %>
    <span>Buscar la dirección en google maps y pegar aquí el link</span>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :event_date %>
    <span>Formato recomendado: Día, mes y año (29 Febrero 2020)</span>
  </div>

  <div class="actions">
    <%= form.submit "Publicar" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="wrap-edit-profile">
  <section class="wrap-edit-profile-center">

    <h1>Editar Evento</h1>

    <div id="tabs-container">

        <ul class="tabs-menu">
            <li class="current"><a href="#tab-1">Info de tu Evento</a></li>
        </ul>

        <div class="tab">

            <div id="tab-1" class="tab-content">

            <%= render 'form', event: @event %>

            <nav class="access-form">
              <ul>
                <li><%= link_to 'Ver Evento', page_event_path(@page, @event) %></li>
              </ul>
            </nav>

            </div>

        </div>
    </div>

  </section>
</section>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Place</th>
      <th>Date</th>
      <th>Page</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.place %></td>
        <td><%= event.date %></td>
        <td><%= event.page %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<section class="wrap-edit-profile">
  <section class="wrap-edit-profile-center">

    <h1>Nuevo evento</h1>
    <p>Ingresa los datos de tu evento nuevo</p>

    <div id="tabs-container">

        <ul class="tabs-menu">
            <li class="current"><a href="#tab-1">Info de tu Evento</a></li>
        </ul>

        <div class="tab">

            <div id="tab-1" class="tab-content">

            <%= render 'form', event: @event %>

            </div>


        </div>
    </div>

  </section>
</section>

app/views/events/show.html.erb
<section class="bg-event-sticky" style="background-image: url('<%= @event.eventimage %>');">
  <div class="bg-trame"></div>
</section>
<section class="show-event">

  <section class="show-event-center">

    <div class="info-event-content">

        <h2><a href=""><img src="<%= @event.page.image %>" alt="<%= @event.page.name %>" title="Foto perfil página <%= @event.page.name %>"></a>
          Realizado por <span><%= @event.page.name %></span></h2>

        <span class="tag">evento atoallae</span>
        <h1><%= @event.title %></h1>
        <p><%= @event.description %></p>

        <nav>
          <ul>
            <% if current_user.liked? @event %>
              <span><i class="fas fa-user-plus"></i> Asistirás a este evento</span>
              <%= link_to 'No asistir', like_page_event_path(@event), method: :put, class: 'no-asistir' %>
            <% else %>
              <%= link_to 'Asistir', like_page_event_path(@event), method: :put %>
            <% end %>

          </ul>
        </nav>

        <div class="asist-event">

          <a href="" class="access-to-asist" data-toggle="modal" data-target="#modalAsistentes">
            <% @event.get_likes.by_type(User)[0,3].each  do | image| %>
            <img src="<%= image.voter.profile.avatar %>" alt="">
            <% end %>
          </a>

          <% if @event.get_likes.size > 0 %>

            <p><span><%= @event.get_likes.by_type(User).last.voter.profile.username %></span>

              <% if @event.get_likes.size.to_i > 1 %>
                y otras <span><%= ( @event.get_likes.size.to_i - 1 ) %></span> personas asistirán al evento
              <% else %>
                asistirá a este evento
              <% end %>
            </p>

          <% end %>

        </div>

    </div>

  </section>

  <!-- Modal de amigos seguidores -->
  <div class="modal fade modal-custom" id="modalAsistentes" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content modal-content-custom">

        <h1>Asistentes al evento
          <% if @event.get_likes.size.to_i > 1 %>
          <span><strong><%= @event.get_likes.size %></strong> personas asistirán</span>
          <% else %>
          <span><strong><%= @event.get_likes.size %></strong> persona asistirá</span>
          <% end %>
          </h1>

        <% @event.get_likes.by_type(User).each  do | user_info| %>

        <div class="asist-content">
          <div class="asist-bloque">
            <img src="<%= user_info.voter.profile.avatar %>" alt="">
            <div class="asist-info">
              <a href="<%= profile_path(user_info.voter.profile) %>"><%= user_info.voter.profile.username %></a>
              <p><%= user_info.voter.profile.username %></p>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>


  <% if (user_signed_in? && @event.user == current_user) %>
  <%= link_to edit_page_event_path(@event.page, @event), class:"editar-evento" do %>
     <i class="far fa-edit"></i> Editar información del evento
   <% end %>
  <% end %>

  <section class="content-body-event">

    <img src="<%= @event.eventimage %>" alt="">

    <div class="info-event-bloque">
      <h1><%= @event.title %></h1>
      <p><%= @event.description %></p>
      <p class="place"><strong>Lugar:</strong> <%= @event.place %></p>
      <a href="<%= @event.map %>" target="_blank" class="maps"><%= image_tag("g-maps.svg", :alt => "Google Maps icono") %> Ver ubicación en Googel Maps</a>
      <p class="date"><strong>Fecha:</strong> <%= @event.date %></p>

    </div>



  </section>


</section>

<p id="notice"><%= notice %></p>

<%= render 'partials/footer-inter' %>