config/routes.rb
Rails.application.routes.draw do

  resources :orders, only:[:create, :index, :destroy]

  get 'home/index'

  resources :pages do
    resources :events do
      member do
        put "like" => "events#like"
      end
    end
    member do
      put "follow" => "pages#follow"
    end
  end

  resources :profiles, only:[:index, :show, :update, :edit]

  get '/my_profile' => 'profiles#profile', as: 'my_profile'
  get '/my_pages' => 'pages#my_pages', as: 'my_pages'
  get '/my_events' => 'events#my_events', as: 'my_events'
  get '/searching' => 'user#searching', as: 'searching'

  resources :products do
    resources :stocks, only:[:index, :create]
  end
  devise_for :controllers

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get '/resultados_busqueda/:search' => 'user#search', as: 'resultados_busqueda'

  put 'follow/:id/:id2' => 'profiles#follow', as: 'follow_profile'

  resources :posts do
    resources :comments, only:[:create]

    member do
      put "like" => "posts#like"
    end
  end

  root to:'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :stocks, :dependent => :destroy


  mount_uploader :imagen, ImagenUploader

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :show]
  load_and_authorize_resource
  skip_authorization_check

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.all.limit(3).order("RANDOM()")
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    # byebug
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save

        params[:product][:stock].to_i.times do
          Stock.create(product_id: @product.id, price: params[:product][:price])
        end

        # TODO: Completar la funcionalidad
        # FIXME: COMENTARIO DE PRUEBA
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id, :imagen)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div class="field field-avatar">
    <%= form.label :imagen, 'Seleccionar Imagen' %>
    <%= form.file_field :imagen, id: :product_imagen %>
  </div>

  <% if !product.id %>

  <div class="field">
    <%= form.label :stock, "Stock Inicial" %>
    <%= form.text_field :stock %>
  </div>

  <div class="field">
    <%= form.label :price, "Precio inicial" %>
    <%= form.text_field :price %>
  </div>

  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, @categories.order(:name), :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit "Publicar" %>
  </div>
<% end %>

app/views/products/create.js.erb
alert("El producto <%= @order.stock.product.name %> fue agregado al carro");

$('#stock-count-store').html('<%= link_to product.stocks.count, product_stocks_path(product)  %> Unidades');

app/views/products/edit.html.erb
<section class="wrap-edit-profile">
  <section class="wrap-edit-profile-center">

    <h1>Editar Producto</h1>

    <div id="tabs-container">

        <ul class="tabs-menu">
            <li class="current"><a href="#tab-1">Info del Producto</a></li>
        </ul>

        <div class="tab">

            <div id="tab-1" class="tab-content">

            <%= render 'form', product: @product %>

            <nav class="access-form">
              <ul>
                <li><%= link_to 'Ver producto', @product %></li>
                <li><%= link_to 'Volver', products_path %></li>
              </ul>
            </nav>

            </div>


        </div>
    </div>

  </section>
</section>

<%= render 'partials/footer-inter' %>

app/views/products/index.html.erb
<section class="wrap-store">
  <section class="wrap-store-head">
    <h1>store
    <span><strong>atoallae</strong> products</span></h1>

    <article class="head-store-con">

      <div class="store-intro">
        <%= image_tag("Logo-atoallae-int.svg", :alt => "Logo Atoallae") %>
        <div class="grid">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <p>Nos dedicamoes exclusivamente a la creación de productos
          que tenga todo el estilo que necesitas para ser el/la mejor.
          Vístete con nuestros productos y disfruta!</p>
      </div>

    </article>

  </section>


  <section class="wrap-store-center">
    <section class="wrap-products-center-inter">
      <h1>productos</h1>
    </section>
  </section>

  <section class="wrap-store-center wrap-store-center-grid">

    <section class="wrap-products-center-inter">

    <% @products.each do |product| %>
    <article class="product">

      <a href=""></a>

      <%= link_to product, class: 'more-info' do %>
        <img src="<%= product.imagen %>" alt="">
        <h1><%= product.name %></h1>
      <% end %>

      <% if current_user.admin? %>

      <nav class="custom-pro">
        <ul>
          <li><%= link_to 'Editar producto', edit_product_path(product) %></li>
          <li><%= link_to 'Eliminar Producto', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </nav>

      <% end %>

      <div class="product-description">
        <div class="bloque-desc">
          <p><%= truncate(product.description, :length => 60) %> <%= link_to 'Ver más', product %> </p>
        </div>
        <div class="bloque-desc">
          <h2><%= number_to_currency(product.stocks.last.price, unit: "$", separator: ",", delimiter: ",", precision: 0) %> CLP</h2>
          <p>Stock: <span id="stock-count-store"><%= link_to product.stocks.count, product_stocks_path(product)  %> Unidades</span></p>

          <nav>
            <ul>
              <li>
              <%= link_to product, class: 'more-info' do %>
                <i class="fas fa-search"></i>
              <% end %>
              </li>
              <li>
                <% if product.stocks.count > 0 %>
                  <%= form_with(model: Order.new) do |form| %>

                    <%= form.hidden_field :stock_id, value: product.stocks.last.id %>

                    <%= button_tag type: 'submit' do %>
                        <i class="fas fa-shopping-cart"></i>
                    <% end %>

                  <% end %>

                <% else %>
                <p>No stock</p>
              <% end %>
              </li>
            </ul>
          </nav>
        </div>
      </div>

    </article>
    <% end %>

    </section>

  </section>

</section>
<%= render 'partials/footer-store' %>

app/views/products/new.html.erb
<section class="wrap-edit-profile">
  <section class="wrap-edit-profile-center">

    <h1>Nuevo Producto</h1>

    <div id="tabs-container">

        <ul class="tabs-menu">
            <li class="current"><a href="#tab-1">Info del Producto</a></li>
        </ul>

        <div class="tab">

            <div id="tab-1" class="tab-content">

            <%= render 'form', product: @product %>

            <nav class="access-form">
              <ul>
                <li><%= link_to 'Volver', products_path %></li>
              </ul>
            </nav>



            </div>

        </div>
    </div>

  </section>
</section>
<%= render 'partials/footer-inter' %>

app/views/products/show.html.erb
<section class="product-show-wrap">
  <section class="product-show-wrap-center">

    <article class="show-product">
      <img src="<%= @product.imagen %>" alt="">
      <%= image_tag("grid_dots.png", :alt => "Dots", :class => 'dots') %>
    </article>
    <article class="show-product">
      <h1><%= @product.name %></h1>
      <% if current_user.admin? %>
      <nav>
        <ul>
          <li><%= link_to 'Editar', edit_product_path(@product) %></li>
          <li><%= link_to 'Volver', products_path %></li>
          <li><%= link_to 'Eliminar', @product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </nav>
      <% end %>

      <h2>Precio: <%= number_to_currency(@product.stocks.last.price, unit: "$", separator: ",", delimiter: ",", precision: 0) %> CLP</h2>
      <p><span>Descripción:</span>
        <%= @product.description %></p>

        <p><span>Stock:</span> <%= @product.stocks.count %> unidad/es</p>

            <% if @product.stocks.count > 0 %>
              <%= form_with(model: Order.new) do |form| %>
                <%= form.hidden_field :stock_id, value: @product.stocks.last.id %>
                <div class="cart-content">
                  <%= image_tag("cart-active.svg", :alt => "Carrito compra") %>
                  <%= form.submit "Agregar al carrito", class: 'cart-access' %>
                </div>

              <% end %>
            <% else %>
              <p>No stock</p>
          <% end %>

        <p class="cat"><strong>Categoría:</strong> <%= @product.category.name %></p>
    </article>

  </section>
</section>

<section class="more-products">
  <section class="more-products-center">
    <h1>Quizá te interese</h1>

    <section class="more-products-grid">

      <% @products.each do |product| %>

      <article class="more-single">
        <img src="<%= product.imagen %>" alt="">
        <div class="more-info">
          <h1><%= product.name %></h1>
          <h2><%= number_to_currency(product.stocks.last.price, unit: "$", separator: ",", delimiter: ",", precision: 0) %> CLP</h2>
          <p><%= truncate(product.description, :length => 60) %></p>

          <%= link_to product, class: 'more-info' do %>
            <i class="fas fa-search"></i> Más info
          <% end %>
        </div>
      </article>

      <% end %>

    </section>

  </section>
</section>
<%= render 'partials/footer-store' %>